# Generated by Django 2.2.16 on 2020-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarW', '0004_misionvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('ident', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
